### ISSUE TITLE
OpenShift: Cannot inject custom CA for oauth endpoint

### ISSUE THREAD

**Issue by X-dark** [jupyterhub/oauthenticator#411]
### Bug description
When using a oauth endpoint with a custom CA on OpenShift, I cannot get the certificate verification to work. It seems that #363 imply that the CA should be in `/run/secrets/kubernetes.io/serviceaccount/ca.crt`. This is only the case for API endpoint not OAuth endpoint (which by default get the wildcard Ingress router certificate).

We can inject the custom CA with a configmap [1] but we cannot overwrite the path above as it is already a mounted secret.

[1] https://docs.openshift.com/container-platform/4.6/networking/configuring-a-custom-pki.html#certificate-injection-using-operators_configuring-a-custom-pki

**Comment by X-dark** [comment]
@manics well seems strange to me to hardcode a cacert which is not guaranteed to contain the CA chain of the OAuth endpoint. Will wait for more feedback on the downstream issue then.

**Comment by wseaton** [comment]
This should hopefully be fixed in https://github.com/jupyterhub/oauthenticator/pull/410 due to us adding support for the `pycurl` backend.

**Comment by galshi** [comment]
@wseaton I see that you've removed the pycurl import from #410, is there a fix in the work for this issue?

**Comment by wseaton** [comment]
@galshi removing the pycurl import shouldn't have affected anything, as it is on by default: https://github.com/jupyterhub/oauthenticator/pull/410#discussion_r574552667

**Comment by galshi** [comment]
@wseaton Thanks, didn't notice that.
Custom CA verification still doesn't work for me though, @X-dark have you been able to solve it?
